### ISSUE TITLE
Same problem from project euler

### ISSUE THREAD

**Issue by Grv-Singh** [michaelfromyeg/vscode-puzzles#13]
`Each time a Problem is requested from Project euler, the same problem is populated with it's markdown file and python file, in my case it is stuck at problem 100`
![image](https://user-images.githubusercontent.com/12825441/119351901-a7cd7480-bcbe-11eb-979e-bf0d20b1dc65.png)

**Comment by michaelfromyeg** [comment]
Hey! You're definitely right, I think I set it up so that it _only_ returns problem 100, since I was hacking things together for the hack-a-thon where this was first built.

...but seeing as I have some real users, I can fix this! I'll have a PR up for it shortly.

I'm thinking of two options:

- [ ] Get a random Project Euler problem (i.e., it generates a number 1 through X)
- [ ] Select a Project Euler problem (i.e., enter a number 1 through X)

Anything else I should add? Also, feel free to send any other feedback you have here: mdemar01@student.ubc.ca.

**Comment by Grv-Singh** [comment]
Hey! Yes, definitely the option one is the best way. Let's choose a random no. b/w 1 & 747. Although this number is dynamic.. it might go up or down. Better to have this number driven by the API as well.. Thanks for this extension sir.. it helps to solve project euler problems in a familiar environment.

**Comment by michaelfromyeg** [comment]
For sure, I think for now I'll use that 747 value as an upper-bound, and in the future will look to check it dynamically... somehow. Glad to hear you're enjoying this project. I should have the PR finished tonight, latest tomorrow.

**Comment by michaelfromyeg** [comment]
New version is [published](https://marketplace.visualstudio.com/items?itemName=michaelfromyeg.vscode-puzzle).

**Comment by Grv-Singh** [comment]
Hey! thanks for the quick update. But you should know the random option is still not working.
![image](https://user-images.githubusercontent.com/12825441/120094243-dc1cb700-c13c-11eb-8572-76e4f5934d33.png)

**Comment by michaelfromyeg** [comment]
@Grv-Singh sorry about this -- just fixed it! There was a bug in the API URL the extension was creating, it's patched in 1.0.2.

**Comment by michaelfromyeg** [comment]
@Grv-Singh just want to follow-up and make sure this is fixed -- is it working for you okay now?

**Comment by Grv-Singh** [comment]
@michaelfromyeg Indeed, it is working as expected. Many thanks for your quick fix!
